name: Build Custom Caddy image

on:
  push:
    branches: ['main']
    paths:
      - 'caddy-image/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: tsuki-tsuki/caddy
  WORKDIR: caddy-image

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Load dotenv vars
        uses: falti/dotenv-action@v1.1.5
        with:
          path: ${{ env.WORKDIR }}/.env
          export-variables: true
          keys-case: bypass

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ env.CADDY_VERSION }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.CADDY_VERSION }}
            type=semver,pattern={{major}},value=${{ env.CADDY_VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: setup-buildx

      - name: Save Docker cache mount
        uses: actions/cache@v5
        id: cache
        with:
          path: cache-mount
          key: cache-mount-${{ hashFiles(format('{0}/{1}',env.WORKDIR,'Dockerfile')) }}

      - name: Restore Docker cache mounts
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-dir: cache-mount
          dockerfile: ${{ env.WORKDIR }}/Dockerfile
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: "${{ env.WORKDIR }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CADDY_VERSION=${{ env.CADDY_VERSION }}
